### ISSUE TITLE
Some questions about the third step self-labeling

### ISSUE THREAD

**Issue by Matthewlliu** [wvangansbeke/Unsupervised-Classification#21] opened 2020-08-07 08:39 UTC
Hello!
I am trying to reproduce the results in the paper on cifar and stl-10, and the code works really fine on cifar-10 and cifar-20 as reported in your paper. However when I try stl-10, I found that the clustering accuracy drops during the entire self-labeling training. 
Then I tried some new datasets. For example, I extracted 10 classes from MiniImageNet ( let's call it mini-10 ), and 5 classes from CUB-200-2011 (cub-5). And I observed the same phenomenon in mini-10 - though the accuracy in the end of step 2 is trained to above 60%, it still drops rapidly in the third step. With an accuracy of 65% at end of step 2 on cub-5, step 3 simply cannot run because no probability can be found above the threshold 0.99 to produce pseudo label.
Wonder if you have ever encountered such problems and how to solve it. Greatly appreciate your answer.

**Comment by wvangansbeke** [comment] 2020-08-07 11:04
Hi @Matthewlliu,

I appreciate you checking out the code!

I recently tested cifar with this repository and got numbers close to ones reported in the paper. I can confirm that self-labeling provides noticable improvements for cifar10, cifar20, imagenet50, imagenet100 and imagenet200. 

Regarding stl10, as you can see from the numbers in the paper, self-labeling doesn't really improve much. It should more or less stay constant from my experience. Sometimes I observed a small drop and sometimes a small improvement. After 10 runs, the average accuracy should be around 75% after clustering. It seems that on average it improves a little bit. We also show an ablation in the paper for different threshold values btw.  Maybe you can try to run it for just 100 epochs during the 2nd step and select the last model, instead of the one with the lowest loss (not sure this will change anything though). Which accuracy do you get actually?

I didn't try it for MiniImagenet or CUB myself. Of course, you always need to have enough samples for every class above the threshold, otherwise there is no point in trying self-labeling. So lowering the threshold might help, but something else might be an issue here (e.g. training time for the pretext task, augmentations, etc). For example for ImageNet, the pretext task is trained for 800 epochs (see MoCo). Anyway, you can always try some of the tricks we used for Imagenet, i.e. multiple heads during step 2 and EMA during step 3 (checkout the config files for more details.). I guess this should solve some of your issues. 

In general, you can not guarantee that the clusters will align perfectly with the ground truth. If the alignment is not good after step 2, self-labeling is not going to provide higher accuracy (the NMI metric might go up though). It simply pushes the clusters away from eachother based on the confident samples it has found during step 2. Semantic clustering is quite ambiguous after all, since there are multiple ways to do so. 

Hope this helps.

**Comment by wvangansbeke** [comment] 2020-08-17 11:08
Hi @Matthewlliu,

Do you still have issues regarding STL10? Otherwise I will close this issue.

**Comment by Matthewlliu** [comment] 2020-08-17 14:51
> Hi @Matthewlliu,
> 
> Do you still have issues regarding STL10? Otherwise I will close this issue.

No. Thank you very much for your answering.

**Closed** 2020-08-17 14:51 UTC
